name: Deploy AWS CDK IaC to AWS

on:
  workflow_call:
    inputs:
      region:
        required: true
        type: string
      oidc_role:
        required: true
        type: string
      environment:
        required: true
        type: string
      project_dir_path:
        required: true
        type: string
      checkout_openapi_yaml:
        required: false
        type: boolean

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ inputs.oidc_role }}
          aws-region: ${{ inputs.region }}

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Deploy CDK App
        env:
          REGION: ${{ inputs.region }}
          ENVIRONMENT: ${{ inputs.environment }}
        working-directory: ${{ inputs.project_dir_path }}
        run: |
          if [ "${{ inputs.checkout_openapi_yaml }}" = true ]
          then
            eval `ssh-agent -s`
            ssh-add - <<< "${{ secrets.CORE_REPO_SSH_KEY }}"
            git clone git@github.com:Aesthetics-360/A360-Core-App.git
            ls -al
          fi

          export CDK_DEFAULT_ACCOUNT=$(aws sts get-caller-identity | jq -r .Account)
          npm i -g aws-cdk@2.139.1
          pip3 install -r requirements.txt
          cdk bootstrap -c env=$ENVIRONMENT -c region=$REGION
          cdk diff -c env=$ENVIRONMENT -c region=$REGION
          cdk deploy --all --require-approval=never -c env=$ENVIRONMENT -c region=$REGION